from time import sleep
from random import randrange
sleep(2)
print("Запуск атаки Пентагона...")
sleep(randrange(1, 5))
print("Атака завершена на 10%...")
sleep(randrange(2, 4))
print("Атака завершена на 20%...")
sleep(randrange(2, 5))
print("Атака завершена на 30%...")
sleep(randrange(2, 5))
print("Атака завершена на 40%...")
sleep(randrange(2, 5))
print("Атака завершена на 50%...")
sleep(randrange(2, 5))
print("Атака завершена на 60%...")
sleep(randrange(2, 5))
print("Атака завершена на 70%...")
sleep(randrange(2, 5))
print("Атака завершена на 80%...")
sleep(randrange(2, 5))
print("Атака завершена на 90%...")
sleep(randrange(2, 5))
print("Атака завершена на 100%...")
sleep(1)
print("Пентагон успешно взломан!")
sleep(1)
print("Получение данных...")
for i in range(50): 
sleep(randrange(2, 5))
print('Даные: idi naxyi')
input()
